[build]
builder = "nixpacks"
buildCommand = "npm install --prefer-offline && npm run build"

[deploy]
startCommand = "node server.js"

[build.env]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "22.13"
